"""crear tablas iniciales del sistema PQR

Revision ID: 0154515dc139
Revises: 
Create Date: 2026-09-13 18:51:20.991010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0154515dc139'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('solicitante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento', sa.String(length=30), nullable=True),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('agente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pqr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('agente_asignado_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('canal', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agente_asignado_id'], ['agente.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['solicitante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguimiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pqr_id', sa.Integer(), nullable=False),
    sa.Column('agente_id', sa.Integer(), nullable=True),
    sa.Column('tipo_accion', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['agente.id'], ),
    sa.ForeignKeyConstraint(['pqr_id'], ['pqr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguimiento')
    op.drop_table('pqr')
    op.drop_table('agente')
    op.drop_table('solicitante')
    op.drop_table('rol')
    # ### end Alembic commands ###
