"""agregar radicado a PQR

Revision ID: 483a66aa0e73
Revises: 0154515dc139
Create Date: 2026-09-13 21:38:35.560167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483a66aa0e73'
down_revision: Union[str, Sequence[str], None] = '0154515dc139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pqr', sa.Column('radicado', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'pqr', ['radicado'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'pqr', type_='unique')
    op.drop_column('pqr', 'radicado')
    # ### end Alembic commands ###
